# Generated by Django 5.0.1 on 2024-01-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='b2bi_companies',
        ),
        migrations.AlterModelTable(
            name='companyaddress',
            table='b2bi_company_addresses',
        ),
        migrations.AlterModelTable(
            name='companygstnumber',
            table='b2bi_company_gst_numbers',
        ),
        migrations.AlterModelTable(
            name='companypaymentmode',
            table='b2bi_company_payment_modes',
        ),
    ]
