# Generated by Django 5.0.1 on 2024-01-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='b2bi_invoices',
        ),
    ]
